routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Maatwebsite\Excel\Facades\Excel;
use App\Exports\Sumo;
use App\Exports\Minisumo;
use App\Exports\Seguidor;
use App\Exports\Dron;

Route::get('/', function () {


return view('auth.login');

});

Route::get('/inicio', function () {
    return view('welcome');
});


Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('products','ProductController');





Route::get('/caldrones', 'DronesController@index2');



Route::get('/caldrones', 'DronesController@index2')->name('caldrones');

Route::get('/resDrones', 'DronesController@index2');
Route::post('/resDronesPost', 'DronesController@index2');


Route::resource('Drones','DronesController');




Route::get('/resSeguidores','SeguidoresController@index2');
Route::post('/resSeguidoresPost','SeguidoresController@index2');
Route::resource('Seguidores','SeguidoresController');



Route::get('/resSumos','SumosController@index2');
Route::get('/ronda-extra-sumos','SumosController@index_extra');
Route::get('/ronda-extra-minisumos','MinisumosController@index_extra');
Route::get('/resMinisumos','MinisumosController@index2');
Route::resource('Sumos','SumosController');
Route::resource('Minisumos','MinisumosController');

Route::post('/Hdrones','HdronController@index');
Route::resource('Hdron','HdronController');

Route::post('/Hseguidor','HseguidoresController@index');
Route::resource('Hseguidores','HseguidoresController');

// Sumos Historial 

Route::post('/Hsumos','HsumoController@index');
Route::resource('Hsumo','HsumoController');

Route::post('/Hminisumos','HminisumoController@index');
Route::resource('Hminisumo','HminisumoController');



Route::get('/sumo-pdf','SumosController@pdf')->name('roles.pdf');


Route::get('/eliminar','SumosController@destroy');

Route::get('/exportsumo', function () {
    return Excel::download(new Sumo, 'sumos.xlsx');
    return view('welcome');
});
Route::get('/exportminisumo', function () {
    return Excel::download(new Minisumo, 'minisumos.xlsx');
    return view('welcome');
});
Route::get('/exportdron', function () {
    return Excel::download(new Dron, 'dron.xlsx');
    return view('welcome');
});
Route::get('/exportseguidor', function () {
    return Excel::download(new Seguidor, 'seguidor.xlsx');
    return view('welcome');
});

resources/views/calificar/calDrones.blade.php
@extends('template.layout')

@section('content')

@if ($message = Session::get('success'))

<div class="alert alert-success">

    <p>{{ $message }}</p>

</div>

@endif

<center> <h1>Calificar de drones</h1></center>
<hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Nombre del robot</th>
      <th scope="col">Institucion</th>
      <th scope="col">Ronda</th>
      <th scope="col">Tiempo</th>
      <th scope="col">Status</th>
      <th scope="col">Calificar</th>
    </tr>
  </thead>
  <tbody>

  @foreach($drones as $dron)
    <tr>
      <th>{{$dron->NombreRobot}}</th>
      <td>{{$dron->Institucion}}</td>
      <td>{{$dron->Ronda}}</td>
      <td>{{$dron->Tiempo}}</td>
      <td>{{$dron->Status}}</td>
      <td>
            <!--<a class="btn btn-primary"  href="{{ route('Drones.edit',$dron->id) }}">Calificar</a>-->
            <a class="btn btn-primary"  href="Drones/{{$dron->id}}/edit">Calificar</a>

            
      </td>
    </tr>    
    @endforeach
  </tbody>
</table>





@endsection('content')

resources/views/calificar/calMinisumo.blade.php
<?php

ini_set('max_execution_time', 300); 

?>



@extends('template.layout')

@section('content')

@if ($message = Session::get('success'))

<div class="alert alert-success">

    <p>{{ $message }}</p>

</div>

@endif


<h2> <p class="text-center"> Calificar Mini-sumos </p> </h2>


    <div class="row">

       <div class="col-md-10">


        <table class="table table-light">
            <thead class="thead-light">
                <tr>
                
        
                    <th>Id</th>
                    <th>Nombre del robot</th>                
                    <th>Escuela</th>
                    <th>Ronda</th>
                    <th>Action</th>  
            
                </tr>
            </thead>
            <tbody>

           


        @foreach($grupo_a as $lista)

                <tr>

                    <td>{{ $lista->id }}</td> 
                    <td>{{ $lista->NombreRobot }}</td> 
                    <td>{{ $lista->Institucion }}</td> 
                    <td>{{ $lista->Ronda }}</td> 
                    <td>
                    <a class="btn btn-primary" 
                       href="{{ route('Minisumos.edit',$lista->id) }}">Calificar
                    </a> 
                    </td>   
                                 
                </tr>

             @endforeach
                
              </tbody>

         </table>

    </div>

 </div>


@endsection

resources/views/calificar/calSeguidor.blade.php
@extends('template.layout')

@section('content')

@if ($message = Session::get('success'))

<div class="alert alert-success">

    <p>{{ $message }}</p>

</div>

@endif


<center> <h1>Calificar de seguidores</h1></center>
<hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Nombre del robot</th>
      <th scope="col">Institucion</th>
      <th scope="col">Ronda</th>
      <th scope="col">Tiempo</th>
      <th scope="col">Status</th>
      <th scope="col">Calificar</th>
    </tr>
  </thead>
  <tbody>

  @foreach($seguidores as $seguidor)
    <tr>
      <th>{{$seguidor->NombreRobot}}</th>
      <td>{{$seguidor->Institucion}}</td>
      <td>{{$seguidor->Ronda}}</td>
      <td>{{$seguidor->Tiempo}}</td>
      <td>{{$seguidor->Status}}</td>
      <td>
    
            <a class="btn btn-primary"  href="Seguidores/{{$seguidor->id}}/edit">Calificar</a>

            
      </td>
    </tr>    
    @endforeach
  </tbody>
</table>





@endsection('content')

resources/views/calificar/calSumos.blade.php
<?php

ini_set('max_execution_time', 300); 

?>



@extends('template.layout')

@section('content')

@if ($message = Session::get('success'))

<div class="alert alert-success">

    <p>{{ $message }}</p>

</div>

@endif


<h2> <p class="text-center"> Calificar Sumos </p> </h2>


    <div class="row">

       <div class="col-md-10">


        <table class="table table-light">
            <thead class="thead-light">
                <tr>
                
        
                    <th>Id</th>
                    <th>Nombre del robot</th>                
                    <th>Escuela</th>
                    <th>Ronda</th>
                    <th>Action</th>  
            
                </tr>
            </thead>
            <tbody>

           


        @foreach($grupo_a as $lista)

                <tr>

                    <td>{{ $lista->id }}</td> 
                    <td>{{ $lista->NombreRobot }}</td> 
                    <td>{{ $lista->Institucion }}</td> 
                    <td>{{ $lista->Ronda }}</td> 
                    <td>
                    <a class="btn btn-primary" 
                       href="{{ route('Sumos.edit',$lista->id) }}">Calificar
                    </a> 
                    </td>   
                                 
                </tr>

             @endforeach
                
              </tbody>

         </table>

    </div>

 </div>


@endsection